import React, { useState } from 'react';
import { BookOpen, Terminal, ShieldCheck, ArrowRight, ExternalLink, Copy, Check, Info, AlertTriangle } from 'lucide-react';

export const DocsView: React.FC = () => {
  const [copiedSnippet, setCopiedSnippet] = useState<string | null>(null);

  const copyToClipboard = async (text: string, id: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedSnippet(id);
      setTimeout(() => setCopiedSnippet(null), 2000);
    } catch {
      // Fallback
    }
  };

  return (
    <div className="space-y-10 max-w-5xl mx-auto">
      {/* Header */}
      <div className="rounded-xl border border-slate-800 bg-[#0d131f] p-6 sm:p-8">
        <div className="flex items-center gap-2 text-xs font-mono text-cyan-400 mb-1">
          <span>MikroTik RouterOS Engineer Handbook</span>
          <span aria-hidden="true">·</span>
          <span>Hossein Golshan</span>
        </div>
        <h1 className="text-2xl font-bold tracking-tight text-white">
          Documentation & Deployment Guide
        </h1>
        <p className="text-sm text-slate-400 mt-2 leading-relaxed">
          Comprehensive instructions for importing, scheduling, and routing with PrefixList address-lists on RouterOS v7 and v6 hardware.
        </p>
      </div>

      {/* Guide 1: Quick Terminal Import */}
      <div className="rounded-xl border border-slate-800/90 bg-[#0d131f] p-6 sm:p-8 space-y-4">
        <div className="flex items-center gap-2">
          <Terminal className="h-5 w-5 text-cyan-400" />
          <h2 className="text-lg font-bold text-white">
            01. Quick Import via RouterOS Terminal
          </h2>
        </div>
        <p className="text-sm text-slate-400 leading-relaxed">
          The fastest way to install any list onto your router is using RouterOS&apos;s built-in <code className="font-mono text-cyan-300">/tool fetch</code> utility. Open Terminal in WinBox, WebFig, or SSH and run:
        </p>

        <div className="relative rounded-lg border border-slate-800 bg-[#070a10] p-4 text-xs font-mono text-cyan-300 select-text">
          <pre>{`/tool fetch url="https://raw.githubusercontent.com/hgolshan/prefixlist/main/public/lists/org/cloudflare.rsc" dst-path="cloudflare.rsc"
/import cloudflare.rsc
/file remove [find name="cloudflare.rsc"]`}</pre>
          <button
            onClick={() =>
              copyToClipboard(
                `/tool fetch url="https://raw.githubusercontent.com/hgolshan/prefixlist/main/public/lists/org/cloudflare.rsc" dst-path="cloudflare.rsc"\n/import cloudflare.rsc\n/file remove [find name="cloudflare.rsc"]`,
                'quick-import'
              )
            }
            className="absolute top-3 right-3 p-1.5 rounded bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700"
            title="Copy snippet"
          >
            {copiedSnippet === 'quick-import' ? (
              <Check className="h-4 w-4 text-emerald-400" />
            ) : (
              <Copy className="h-4 w-4" />
            )}
          </button>
        </div>

        <div className="text-xs text-slate-400 leading-relaxed">
          <strong className="text-slate-200">What happens:</strong> The router downloads the pre-aggregated script from the stable raw GitHub branch, executes the idempotent <code className="font-mono text-cyan-300">/ip firewall address-list</code> rules, and deletes the temporary file to preserve internal NAND flash memory.
        </div>
      </div>

      {/* Guide 2: Idempotent Address-List Architecture */}
      <div className="rounded-xl border border-slate-800/90 bg-[#0d131f] p-6 sm:p-8 space-y-4">
        <div className="flex items-center gap-2">
          <ShieldCheck className="h-5 w-5 text-cyan-400" />
          <h2 className="text-lg font-bold text-white">
            02. Idempotent Updates & Memory Protection
          </h2>
        </div>
        <p className="text-sm text-slate-400 leading-relaxed">
          Standard MikroTik scripts commonly fail when run multiple times because duplicate entries throw errors or inflate table sizes. Every script generated by PrefixList follows strict idempotency:
        </p>

        <div className="relative rounded-lg border border-slate-800 bg-[#070a10] p-4 text-xs font-mono text-slate-300 select-text leading-relaxed">
          <div className="text-slate-500 italic"># 1. Safely purge existing entries for this list only</div>
          <div className="text-cyan-400">/ip firewall address-list</div>
          <div className="text-sky-300">remove [find list=&quot;MY_LIST&quot; comment=&quot;PrefixList&quot;]</div>
          <div className="mt-2 text-slate-500 italic"># 2. Add refreshed, deduplicated subnets atomically</div>
          <div className="text-sky-300">add address=1.0.0.0/24 list=&quot;MY_LIST&quot; comment=&quot;PrefixList&quot;</div>
          <div className="text-sky-300">add address=1.1.1.0/24 list=&quot;MY_LIST&quot; comment=&quot;PrefixList&quot;</div>
        </div>

        <div className="text-xs text-slate-400 leading-relaxed">
          By scoping the removal condition strictly to <code className="font-mono text-cyan-300">comment=&quot;PrefixList&quot;</code>, your custom manual entries inside the same address list remain untouched.
        </div>
      </div>

      {/* Guide 3: RouterOS v7 Policy Routing Best Practices */}
      <div className="rounded-xl border border-slate-800/90 bg-[#0d131f] p-6 sm:p-8 space-y-4">
        <div className="flex items-center gap-2">
          <BookOpen className="h-5 w-5 text-cyan-400" />
          <h2 className="text-lg font-bold text-white">
            03. RouterOS v7 Policy Routing & FastTrack
          </h2>
        </div>
        <p className="text-sm text-slate-400 leading-relaxed">
          If you are routing traffic through a VPN interface (WireGuard, OpenVPN, L2TP) or second WAN provider in RouterOS v7:
        </p>

        <ol className="list-decimal list-inside space-y-2 text-xs sm:text-sm text-slate-300 leading-relaxed">
          <li>
            <strong className="text-white">Routing Tables require FIB:</strong> In RouterOS v7, a routing table must have <code className="font-mono text-cyan-300">fib</code> set; otherwise packets will not be forwarded.
          </li>
          <li>
            <strong className="text-white">Connection Mark before Routing Mark:</strong> Marking the connection first in Mangle (<code className="font-mono text-cyan-300">action=mark-connection</code>) and then marking routing ensures symmetric reply handling and lowers CPU load by skipping evaluation for ongoing packets.
          </li>
          <li>
            <strong className="text-white">FastTrack Conflict:</strong> FastTrack bypasses mangle marks. Ensure you have an <code className="font-mono text-cyan-300">action=accept</code> rule placed before <code className="font-mono text-cyan-300">action=fasttrack-connection</code> for your PBR connection mark.
          </li>
        </ol>
      </div>

      {/* Guide 4: Stable Raw GitHub URLs */}
      <div className="rounded-xl border border-slate-800/90 bg-[#0d131f] p-6 sm:p-8 space-y-4">
        <div className="flex items-center gap-2">
          <Info className="h-5 w-5 text-cyan-400" />
          <h2 className="text-lg font-bold text-white">
            04. Stable Raw GitHub URL Specifications
          </h2>
        </div>
        <p className="text-sm text-slate-400 leading-relaxed">
          All prebuilt files are served over HTTPS directly from GitHub Pages and the raw repository branch. You can rely on these permanent URL patterns in production scripts:
        </p>

        <div className="space-y-2 text-xs font-mono">
          <div className="p-3 rounded-lg bg-slate-900 border border-slate-800 flex items-center justify-between gap-2">
            <span className="text-slate-400">Organization Lists:</span>
            <code className="text-cyan-300 break-all">
              https://raw.githubusercontent.com/hgolshan/prefixlist/main/public/lists/org/&#123;slug&#125;.rsc
            </code>
          </div>
          <div className="p-3 rounded-lg bg-slate-900 border border-slate-800 flex items-center justify-between gap-2">
            <span className="text-slate-400">Country Lists:</span>
            <code className="text-cyan-300 break-all">
              https://raw.githubusercontent.com/hgolshan/prefixlist/main/public/lists/countries/&#123;iso2&#125;.rsc
            </code>
          </div>
          <div className="p-3 rounded-lg bg-slate-900 border border-slate-800 flex items-center justify-between gap-2">
            <span className="text-slate-400">Full Catalog Index:</span>
            <code className="text-cyan-300 break-all">
              https://raw.githubusercontent.com/hgolshan/prefixlist/main/public/lists/index.json
            </code>
          </div>
        </div>
      </div>

      {/* Guide 5: Attribution, Data Sources & Author */}
      <div className="rounded-xl border border-slate-800/90 bg-[#0d131f] p-6 sm:p-8 space-y-6">
        <div>
          <h2 className="text-lg font-bold text-white">
            05. Upstream Data Sources & Author Attribution
          </h2>
          <p className="text-sm text-slate-400 mt-1 leading-relaxed">
            PrefixList aggregates and optimizes authoritative open routing information from global networking registries.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
          <div className="p-4 rounded-lg bg-slate-900/60 border border-slate-800 space-y-1.5">
            <div className="font-semibold text-cyan-400">RIPE NCC (RIPEstat Data API)</div>
            <p className="text-slate-400 leading-relaxed">
              Provides announced BGP autonomous system prefixes, historical routing telemetry, and global routing tables.
            </p>
          </div>
          <div className="p-4 rounded-lg bg-slate-900/60 border border-slate-800 space-y-1.5">
            <div className="font-semibold text-cyan-400">IPdeny & Regional Internet Registries</div>
            <p className="text-slate-400 leading-relaxed">
              Aggregates national delegated country IP blocks from ARIN, RIPE NCC, APNIC, LACNIC, and AFRINIC.
            </p>
          </div>
        </div>

        <div className="p-4 rounded-lg bg-gradient-to-r from-slate-900 via-slate-900/80 to-[#101b2b] border border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <div className="text-sm font-semibold text-white">Created by Hossein Golshan</div>
            <div className="text-xs text-slate-400 mt-0.5">
              Network Engineer &middot; Open-Source Creator &middot; <a href="https://github.com/hgolshan" target="_blank" rel="noopener noreferrer" className="text-cyan-400 hover:underline">github.com/hgolshan</a>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <a
              href="https://github.com/hgolshan/prefixlist"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg bg-cyan-600 hover:bg-cyan-500 text-white transition-colors"
            >
              Star on GitHub
              <ExternalLink className="h-3.5 w-3.5" />
            </a>
          </div>
        </div>
      </div>

      {/* Footer Info */}
      <div className="border-t border-slate-800 pt-6 text-center text-xs text-slate-500">
        PrefixList &copy; {new Date().getFullYear()} Hossein Golshan · Licensed under MIT · Hosted on GitHub Pages
      </div>
    </div>
  );
};
