/**
 * MikroTik RouterOS Configuration & Address List Generator
 * Author: Hossein Golshan
 * Target: RouterOS v7 & v6
 */

export interface GeneratorOptions {
  listName: string;
  ipv4Prefixes: string[];
  ipv6Prefixes: string[];
  includeIPv4?: boolean;
  includeIPv6?: boolean;
  comment?: string;
  sourceUrl?: string;
  sourceName?: string;
  includePolicyRouting?: boolean;
  policyRouting?: {
    tableName: string;
    gateway: string;
    lanInterfaceList: string;
    routingMark: string;
    bypassFastTrack: boolean;
  };
  includeAutoUpdater?: boolean;
  autoUpdater?: {
    scriptName: string;
    scheduleInterval: string; // e.g. "7d"
    startTime: string; // e.g. "03:00:00"
    rawUrl: string;
  };
}

export function formatUtcTimestamp(): string {
  const d = new Date();
  return d.toISOString().replace('T', ' ').substring(0, 19) + ' UTC';
}

/**
 * Generate a complete, production-ready RouterOS .rsc script
 */
export function generateRouterOsScript(options: GeneratorOptions): string {
  const {
    listName = 'PREFIXLIST',
    ipv4Prefixes = [],
    ipv6Prefixes = [],
    includeIPv4 = true,
    includeIPv6 = true,
    comment = 'PrefixList',
    sourceUrl = 'https://raw.githubusercontent.com/hgolshan/prefixlist/main/public/lists/',
    sourceName = 'Custom Selection',
    includePolicyRouting = false,
    policyRouting = {
      tableName: 'to_vpn',
      gateway: 'wireguard1',
      lanInterfaceList: 'LAN',
      routingMark: 'to_vpn',
      bypassFastTrack: true,
    },
    includeAutoUpdater = false,
    autoUpdater = {
      scriptName: `update-prefixlist-${listName}`,
      scheduleInterval: '7d',
      startTime: '03:30:00',
      rawUrl: sourceUrl,
    },
  } = options;

  const timestamp = formatUtcTimestamp();
  const safeListName = listName.trim().replace(/[^a-zA-Z0-9_\-\.]/g, '_') || 'PREFIXLIST';
  const effectiveIpv4 = includeIPv4 ? ipv4Prefixes : [];
  const effectiveIpv6 = includeIPv6 ? ipv6Prefixes : [];
  const totalPrefixes = effectiveIpv4.length + effectiveIpv6.length;

  const lines: string[] = [];

  // 1. Mandatory Banner
  lines.push('# =====================================================================');
  lines.push('# PrefixList - MikroTik RouterOS Address List Kit');
  lines.push('# Generated by: Hossein Golshan');
  lines.push('# GitHub: https://github.com/hgolshan/prefixlist');
  lines.push('# Web App: https://hgolshan.github.io/prefixlist/');
  lines.push(`# Target List: "${safeListName}"`);
  lines.push(`# Content Source: ${sourceName}`);
  lines.push(`# IPv4 Prefixes: ${effectiveIpv4.length} | IPv6 Prefixes: ${effectiveIpv6.length} | Total: ${totalPrefixes}`);
  lines.push(`# Generated At: ${timestamp}`);
  lines.push('#');
  lines.push('# Quick Import in RouterOS Terminal:');
  lines.push(`#   /tool fetch url="${sourceUrl}" dst-path="${safeListName}.rsc"`);
  lines.push(`#   /import ${safeListName}.rsc`);
  lines.push('# =====================================================================');
  lines.push('');

  // 2. IPv4 Address List (Idempotent cleanup and atomic addition)
  if (includeIPv4 && effectiveIpv4.length > 0) {
    lines.push('# ---------------------------------------------------------------------');
    lines.push(`# IPv4 Firewall Address List: [${safeListName}] (${effectiveIpv4.length} entries)`);
    lines.push('# ---------------------------------------------------------------------');
    lines.push('/ip firewall address-list');
    lines.push(`remove [find list="${safeListName}" comment="${comment}"]`);
    for (const prefix of effectiveIpv4) {
      lines.push(`add address=${prefix} list="${safeListName}" comment="${comment}"`);
    }
    lines.push('');
  }

  // 3. IPv6 Address List (Idempotent cleanup and addition)
  if (includeIPv6 && effectiveIpv6.length > 0) {
    lines.push('# ---------------------------------------------------------------------');
    lines.push(`# IPv6 Firewall Address List: [${safeListName}] (${effectiveIpv6.length} entries)`);
    lines.push('# ---------------------------------------------------------------------');
    lines.push('/ipv6 firewall address-list');
    lines.push(`remove [find list="${safeListName}" comment="${comment}"]`);
    for (const prefix of effectiveIpv6) {
      lines.push(`add address=${prefix} list="${safeListName}" comment="${comment}"`);
    }
    lines.push('');
  }

  // 4. Policy Routing (RouterOS v7 syntax)
  if (includePolicyRouting && policyRouting) {
    const table = policyRouting.tableName || 'to_vpn';
    const gw = policyRouting.gateway || 'wireguard1';
    const lan = policyRouting.lanInterfaceList || 'LAN';
    const mark = policyRouting.routingMark || table;
    const connMark = `conn_${mark}`;

    lines.push('# =====================================================================');
    lines.push('# Optional Extra: Policy-Based Routing (PBR) for RouterOS v7');
    lines.push(`# Directs traffic for [${safeListName}] through gateway [${gw}]`);
    lines.push('# =====================================================================');
    lines.push('');
    lines.push('# 1. Create Dedicated Routing Table with Forwarding Information Base (fib)');
    lines.push('/routing table');
    lines.push(`:if ([:len [find name="${table}"]] = 0) do={`);
    lines.push(`  add name="${table}" fib comment="PrefixList PBR Table for ${safeListName}"`);
    lines.push('}');
    lines.push('');
    lines.push('# 2. Add Route into the Custom Routing Table');
    lines.push('/ip route');
    lines.push(`:if ([:len [find routing-table="${table}" dst-address=0.0.0.0/0]] = 0) do={`);
    lines.push(`  add dst-address=0.0.0.0/0 gateway=${gw} routing-table="${table}" check-gateway=ping distance=1 comment="PrefixList Default PBR Route"`);
    lines.push('}');
    lines.push('');
    lines.push('# 3. Firewall Mangle Rules (Prerouting)');
    lines.push('/ip firewall mangle');
    lines.push('# Remove older PrefixList mangle rules for this list');
    lines.push(`remove [find comment="PrefixList PBR [${safeListName}]"]`);
    lines.push(`add chain=prerouting in-interface-list=${lan} dst-address-list="${safeListName}" connection-state=new action=mark-connection new-connection-mark=${connMark} passthrough=yes comment="PrefixList PBR [${safeListName}]"`);
    lines.push(`add chain=prerouting in-interface-list=${lan} connection-mark=${connMark} action=mark-routing new-routing-mark="${table}" passthrough=no comment="PrefixList PBR [${safeListName}]"`);
    lines.push('');

    if (policyRouting.bypassFastTrack) {
      lines.push('# 4. FastTrack Firewall Exclusion Warning & Rule');
      lines.push('# RouterOS FastTrack bypasses mangle marks on active connections.');
      lines.push('# This rule accepts established PBR connections before they can hit FastTrack:');
      lines.push('/ip firewall filter');
      lines.push(`remove [find comment="PrefixList FastTrack Bypass [${safeListName}]"]`);
      lines.push(`:local ftIndex [find action=fasttrack-connection]`);
      lines.push(`:if ([:len $ftIndex] > 0) do={`);
      lines.push(`  add chain=forward action=accept connection-state=established,related connection-mark=${connMark} place-before=$ftIndex comment="PrefixList FastTrack Bypass [${safeListName}]"`);
      lines.push(`} else={`);
      lines.push(`  add chain=forward action=accept connection-state=established,related connection-mark=${connMark} comment="PrefixList FastTrack Bypass [${safeListName}]"`);
      lines.push(`}`);
      lines.push('');
    }
  }

  // 5. Safe Auto-Updater Script & Scheduler
  if (includeAutoUpdater && autoUpdater) {
    const scriptName = autoUpdater.scriptName || `update-${safeListName}`;
    const fetchUrl = autoUpdater.rawUrl || sourceUrl;
    const interval = autoUpdater.scheduleInterval || '7d';
    const startTime = autoUpdater.startTime || '03:00:00';
    const tempFile = `pl_tmp_${safeListName}.rsc`;

    lines.push('# =====================================================================');
    lines.push('# Optional Extra: Safe Automated Weekly Updater');
    lines.push('# Safeguards: Downloads to temp file, verifies file size, keeps old list on error');
    lines.push('# =====================================================================');
    lines.push('/system script');
    lines.push(`remove [find name="${scriptName}"]`);
    lines.push(`add name="${scriptName}" dont-require-permissions=no source="\\`);
    lines.push(`:local listName \\"${safeListName}\\";\\`);
    lines.push(`:local fetchUrl \\"${fetchUrl}\\";\\`);
    lines.push(`:local tempFile \\"${tempFile}\\";\\`);
    lines.push(`:local logPrefix \\"PrefixList-Updater ($listName):\\";\\`);
    lines.push(`:log info (\\\"$logPrefix Starting fetch from \\\" . \\$fetchUrl);\\`);
    lines.push(`:do {\\`);
    lines.push(`  /tool fetch url=\\$fetchUrl dst-path=\\$tempFile mode=https keep-result=yes;\\`);
    lines.push(`} on-error={\\`);
    lines.push(`  :log warning (\\\"$logPrefix Download failed! Network unreachable. Preserving current list.\\\");\\`);
    lines.push(`  :error \\\"Fetch error\\\";\\`);
    lines.push(`};\\`);
    lines.push(`:delay 2s;\\`);
    lines.push(`:local fItem [/file find name=\\$tempFile];\\`);
    lines.push(`:if ([:len \\$fItem] > 0) do={\\`);
    lines.push(`  :local fSize [/file get \\$fItem size];\\`);
    lines.push(`  :if (\\$fSize > 80) do={\\`);
    lines.push(`    :log info (\\\"$logPrefix Verified non-empty file (\\\" . \\$fSize . \\\" bytes). Importing...\\\");\\`);
    lines.push(`    :do {\\`);
    lines.push(`      /import file-name=\\$tempFile;\\`);
    lines.push(`      :log info (\\\"$logPrefix Import successful for \\\" . \\$listName);\\`);
    lines.push(`    } on-error={\\`);
    lines.push(`      :log error (\\\"$logPrefix Import failed with syntax error! Old entries preserved.\\\");\\`);
    lines.push(`    };\\`);
    lines.push(`  } else={\\`);
    lines.push(`    :log warning (\\\"$logPrefix Downloaded file is too small or corrupt (\\\" . \\$fSize . \\\" bytes). Aborting.\\\");\\`);
    lines.push(`  };\\`);
    lines.push(`  /file remove \\$fItem;\\`);
    lines.push(`} else={\\`);
    lines.push(`  :log warning (\\\"$logPrefix Temp file not found on disk. Aborting.\\\");\\`);
    lines.push(`};\\`);
    lines.push('"');
    lines.push('');
    lines.push('/system scheduler');
    lines.push(`remove [find name="sched-${scriptName}"]`);
    lines.push(`add name="sched-${scriptName}" start-time=${startTime} interval=${interval} on-event="${scriptName}" comment="PrefixList Weekly Sync for ${safeListName}"`);
    lines.push('');
  }

  lines.push('# End of PrefixList RouterOS Configuration');
  return lines.join('\n');
}

/**
 * Generate a standalone Safe Auto-Updater script snippet
 */
export function generateAutoUpdaterScriptOnly(
  listName: string,
  rawUrl: string,
  interval = '7d',
  startTime = '03:00:00'
): string {
  const safeListName = listName.trim().replace(/[^a-zA-Z0-9_\-\.]/g, '_') || 'PREFIXLIST';
  const scriptName = `update-prefixlist-${safeListName}`;
  const tempFile = `pl_tmp_${safeListName}.rsc`;

  return `# =====================================================================
# Safe Auto-Updater for MikroTik RouterOS
# List: ${safeListName}
# Author: Hossein Golshan
# Target URL: ${rawUrl}
# =====================================================================

/system script
remove [find name="${scriptName}"]
add name="${scriptName}" dont-require-permissions=no source="\\
:local listName \\"${safeListName}\\";\\
:local fetchUrl \\"${rawUrl}\\";\\
:local tempFile \\"${tempFile}\\";\\
:local logTag \\"PrefixList-Updater [${safeListName}]:\\";\\
:log info (\\\"$logTag Initiating secure fetch from \\\" . \\$fetchUrl);\\
:do {\\
  /tool fetch url=\\$fetchUrl dst-path=\\$tempFile mode=https keep-result=yes;\\
} on-error={\\
  :log warning (\\\"$logTag Fetch failed! Network unreachable. Preserving existing firewall entries.\\\");\\
  :error \\\"Fetch failed\\\";\\
};\\
:delay 2s;\\
:local fItem [/file find name=\\$tempFile];\\
:if ([:len \\$fItem] > 0) do={\\
  :local fSize [/file get \\$fItem size];\\
  :if (\\$fSize > 80) do={\\
    :log info (\\\"$logTag Verified non-empty file (\\\" . \\$fSize . \\\" bytes). Importing...\\\");\\
    :do {\\
      /import file-name=\\$tempFile;\\
      :log info (\\\"$logTag Address-list updated successfully!\\\");\\
    } on-error={\\
      :log error (\\\"$logTag Import failed! Existing address list preserved.\\\");\\
    };\\
  } else={\\
    :log warning (\\\"$logTag Downloaded file is truncated (\\\" . \\$fSize . \\\" bytes). Aborting.\\\");\\
  };\\
  /file remove \\$fItem;\\
} else={\\
  :log warning (\\\"$logTag Downloaded file missing from disk.\\\");\\
};\\
"

# Add automated scheduler (Default: Every 7 days at ${startTime})
/system scheduler
remove [find name="sched-${scriptName}"]
add name="sched-${scriptName}" start-time=${startTime} interval=${interval} on-event="${scriptName}" comment="PrefixList Weekly Sync"
`;
}
